# 这个服务的端口号
server:
  port: 8081
# dubbo 服务名
dubbo:
  application:
    name: provider-server
  registry:
    address: zookeeper://192.168.114.131:2181
    timeout: 60000
  scan:
    base-packages: com.provider.services